// some bootloaders
//
// Start Address
// 0023: RK Disk Bootstrap
// 7777: Paper Tape Binary Loader
//

initial
begin
   //   
   // RK Disk Bootstrap
   //   
   mem['o0023]='o6007; // CAF    ; 
   mem['o0024]='o6744; // DLCA   ; addr = 0
   mem['o0025]='o1032; // TAD(32); unit no
   mem['o0026]='o6746; // DLDC   ; command, unit
   mem['o0027]='o6743; // DLAG   ; disk addr, go
   mem['o0030]='o1032; // TAD(32); unit no, for OS
   mem['o0031]='o5031; // JMP .  ;
   mem['o0032]='o0000; //        ; unit 0 (bit<9:10>)
   //   
   // Binary Loader (Paper Tape)
   // memory data generated by ptp2v from "dec-08-lbaa-pm"
   //
   mem['o7612]='o0000;
   mem['o7613]='o0000;
   mem['o7614]='o0000;
   mem['o7615]='o0000;
   mem['o7616]='o0000;
   mem['o7617]='o1212;
   mem['o7620]='o7402;
   mem['o7621]='o7402;
   mem['o7622]='o7402;
   mem['o7623]='o7402;
   mem['o7624]='o7402;
   mem['o7625]='o7402;
   mem['o7626]='o0000;
   mem['o7627]='o3212;
   mem['o7630]='o4260;
   mem['o7631]='o1300;
   mem['o7632]='o7750;
   mem['o7633]='o5237;
   mem['o7634]='o2212;
   mem['o7635]='o7040;
   mem['o7636]='o5227;
   mem['o7637]='o1212;
   mem['o7640]='o7640;
   mem['o7641]='o5230;
   mem['o7642]='o1214;
   mem['o7643]='o0274;
   mem['o7644]='o1341;
   mem['o7645]='o7510;
   mem['o7646]='o2226;
   mem['o7647]='o7750;
   mem['o7650]='o5626;
   mem['o7651]='o1214;
   mem['o7652]='o0256;
   mem['o7653]='o1257;
   mem['o7654]='o3213;
   mem['o7655]='o5230;
   mem['o7656]='o0070;
   mem['o7657]='o6201;
   mem['o7660]='o0000;
   mem['o7661]='o0000;
   mem['o7662]='o6031;
   mem['o7663]='o5262;
   mem['o7664]='o6036;
   mem['o7665]='o3214;
   mem['o7666]='o1214;
   mem['o7667]='o5660;
   mem['o7670]='o6011;
   mem['o7671]='o5270;
   mem['o7672]='o6016;
   mem['o7673]='o5265;
   mem['o7674]='o0300;
   mem['o7675]='o4343;
   mem['o7676]='o7041;
   mem['o7677]='o1215;
   mem['o7700]='o7402;
   mem['o7701]='o6032;
   mem['o7702]='o6014;
   mem['o7703]='o6214;
   mem['o7704]='o1257;
   mem['o7705]='o3213;
   mem['o7706]='o7604;
   mem['o7707]='o7700;
   mem['o7710]='o1353;
   mem['o7711]='o1352;
   mem['o7712]='o3261;
   mem['o7713]='o4226;
   mem['o7714]='o5313;
   mem['o7715]='o3215;
   mem['o7716]='o1213;
   mem['o7717]='o3336;
   mem['o7720]='o1214;
   mem['o7721]='o3376;
   mem['o7722]='o4260;
   mem['o7723]='o3355;
   mem['o7724]='o4226;
   mem['o7725]='o5275;
   mem['o7726]='o4343;
   mem['o7727]='o7420;
   mem['o7730]='o5336;
   mem['o7731]='o3216;
   mem['o7732]='o1376;
   mem['o7733]='o1355;
   mem['o7734]='o1215;
   mem['o7735]='o5315;
   mem['o7736]='o6201;
   mem['o7737]='o3616;
   mem['o7740]='o2216;
   mem['o7741]='o7600;
   mem['o7742]='o5332;
   mem['o7743]='o0000;
   mem['o7744]='o1376;
   mem['o7745]='o7106;
   mem['o7746]='o7006;
   mem['o7747]='o7006;
   mem['o7750]='o1355;
   mem['o7751]='o5743;
   mem['o7752]='o5262;
   mem['o7753]='o0006;
   mem['o7754]='o0000;
   mem['o7755]='o0000;

   // Paper Tape Binary Loader
   mem['o7777]='o5301; // JMP 7701

// PC=7777 and HALT on RESET
//   mem['o7776]='o7777; // set start address here
//   mem['o7777]='o5776; // JMP I 7776

//   mem['o7776]='o0023;
//   mem['o7777]='o5776; // JMP(7776)=23


end
