M48
; DRILL file {KiCad 9.0.6} date 2026-01-12T10:04:15+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-12T10:04:15+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X5.08Y-5.08
X5.08Y-93.98
X93.98Y-5.08
X93.98Y-93.98
M30
