/*
 * ptp2v.c
 * Paper Tape Binary Data to Verilog mem file converter
 *
 * 2026/01/23
 * by Ryo Mukai
 */

#include <stdio.h>
#include <stdlib.h>

#define BUFLEN 256

#define MODE_WAIT0200
#define MODE_WAITBODY
#define MODE_INBODY

int main(int argc, char *argv[]){
  FILE *fp;
  int hi, lo, data;
  int last_csum, csum;
  int address;
  int field;
  int cnt;
  int start;
  char *buf;
  int leader_cnt;
  int rim_mode;
  
  if(argc <= 1){
    fp = stdin;
  } else {
    char *infile = argv[1];
    if((fp = fopen(infile, "r")) == NULL){
      fprintf(stderr, "%s: Cannot open file '%s'\n", argv[0], infile);
      exit(1);
    }
    printf("// memory data generated by ptp2v from \"%s\"\n", infile);
  }
  printf("// to be included from the top module at the compile\n\n");
  printf("initial\n");
  printf("begin\n");
  
  buf = (char *)malloc(BUFLEN);
  buf[0] = 0;
  
  start = -1;
  cnt = leader_cnt = 0;
  address = field = hi = lo = data = 0;
  for(;;){
    if((hi = fgetc(fp)) == EOF) break;
    cnt++;
    if(start <= 0){
      if(hi == 0){
	start = -1; // wait for 0200
	continue; // skip zero
      } else if(hi == 0200){
	start = 0; // wait for not (0 or 0200)
	continue;
      } else if(start == 0){
	start = 1;
	csum = 0;
      } else {
	start = -1;
	continue;
      }
    }
    if((hi & 0300) == 0300){ // change field
      field = (hi >> 3) & 07;
      printf("%s", buf);
      buf[0] = 0;
      printf("// field = %o\n", field);
      continue;
    }

    if(hi & 0200){
      if(hi != 0200){
	printf("// data error? at %o, hi=%04o\n",cnt-1, hi);
      }
      if( rim_mode ){
	printf("%s", buf);
      } else {
	if(last_csum == (data & 07777)){
	  printf("// checksum=%o OK. (%o)\n", last_csum, cnt-1);
	} else {
	  printf("// checksum error?, csum=%04o, data=%04o (%o)\n",
		 last_csum, (data&07777), cnt-1);
	}
      }
      start = 0;
      buf[0] = 0;
      continue;
    }
    if((lo = fgetc(fp)) == EOF) break;
    cnt++;
    printf("%s", buf);
    last_csum = csum;
    csum = (csum + hi + lo) & 07777;
    buf[0] = 0;
    
    if(hi & 0100){
      if(lo > 077){
	printf("// data error? at %o, hi=%04o, lo=%04o\n",cnt-1, hi, lo);
      }
      address = ((hi&077)<<6) | (lo&077);
      printf("// address=%04o (%o)\n", address, cnt-1);
      rim_mode = 2;
    } else {
      if(rim_mode != 0) rim_mode--;
      data = (hi << 6 | lo) & 07777;
      sprintf(buf, "   mem['o%04o]='o%04o;\n", (field << 12) | address, data);
      address++;
    }
  }
  printf("\n");
  printf("// PC=7777 and HALT on RESET\n");
  printf("   mem['o7776]='o7777; // set start address here\n");
  printf("   mem['o7777]='o5776; // JMP I 7776\n");
  printf("end\n");
}
